name: pandas-flavor
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas>=0.23
  - xarray
  - pip
  - pre-commit
  - pytest  # for tests
  - black # code formatting
  - twine # for uploading to PyPI
  - bump2version
  - pip:
      - lazy-loader
      - tuna
